### ISSUE TITLE
Feature Request: More than two rings

### ISSUE THREAD

**Issue by DNewman5** [Focamacho/RingsOfAscension#55] opened 2021-07-02 02:12 UTC
A config option to enable wearing 4 rings would be awesome.
Fabric version 1.17

**Comment by Wolfy8198** [comment] 2021-12-23 20:37
You can change the amount of ring slots you have using a datapack. I can make you a datapack that allows you to have 4 offhand/ring slots, if you want.

**Comment by focamacho** [comment] 2022-01-18 11:37
Duplicate of #67

**Closed as completed by focamacho** 2022-01-18 11:37 UTC
Labels: enhancement
