### ISSUE TITLE
dungeon loot chests empty

### ISSUE THREAD

**Issue by CuchilloMucho** [Focamacho/RingsOfAscension#2] opened 2020-05-14 04:14 UTC
log:
(https://github.com/Focamacho/RingsOfAscension/files/4626003/2020-05-09-4.log.gz)

modlist: 

Additional Enchanted Miner | Kotori316 | AdditionalEnchantedMiner-1.15.2-15.2.8.jar |  
[2020-05-09-4.log.gz]
  | Apotheosis | Shadows_of_Fire | Apotheosis-1.15.2-3.0.7.jar |  
  | AppleSkin | squeek502 | AppleSkin-mc1.15.2-forge-1.0.13.jar |  
  | AutoRegLib | Vazkii | AutoRegLib-1.5-40.jar |  
  | Bambootiful | bageldotjpg | bambootiful-1.15.2-1.1.3.jar |  
  | Biomes O' Plenty | Forstride | BiomesOPlenty-1.15.2-10.0.0.345-universal.jar |  
  | BloodCraft 5 | wadihw1 | Bloodcraft 5 1.15.2 1.0.9.jar |  
  | Blue Power | Quetzi | bluepower-1.15.2-0.4.188-alpha-universal.jar |  
  | Bonsai Trees 2 | davenonymous | BonsaiTrees-2.1.2.6.jar |  
  | Bookshelf | DarkhaxDev | Bookshelf-1.15.2-5.5.34.jar |  
  | Botania | Vazkii | Botania-r1.15-384.jar |  
  | Building Gadgets | Direwolf20 | buildinggadgets-3.3.5.jar |  
  | Caelus API | TheIllusiveC4 | caelus-FORGE-1.15.2-2.0-beta2.jar |  
  | CC: Tweaked | SquidDev | cc-tweaked-1.15.2-1.87.1.jar |  
  | ChunkNoGoByeBye | LexManos | ChunkNoGoByeBye-1.15.2-1.2.0.jar |  
  | Click Machine | Shadows_of_Fire | ClickMachine-1.15.2-3.0.2.jar |  
  | CoFH Core | TeamCoFH | cofh_core-1.15.2-0.4.0b.jar |  
  | Colytra | TheIllusiveC4 | colytra-FORGE-1.15.2-3.0.jar |  
  | Corail Recycler | Corail_31 | corail_recycler-4.0.4-1.15.2.jar |  
  | Cosmetic Armor Reworked | LainMI | CosmeticArmorReworked-1.15.2-v3a.jar |  
  | Crafting Tweaks | BlayTheNinth | CraftingTweaks_1.15.1-11.0.0.jar |  
  | Cucumber Library | BlakeBr0 | Cucumber-1.15.2-3.0.5.jar |  
  | Curio of Undying | TheIllusiveC4 | curioofundying-FORGE-1.15.2-3.0.jar |  
  | Curios API | TheIllusiveC4 | curios-FORGE-1.15.2-2.0.2.2.jar |  
  | Curious Elytra | TheIllusiveC4 | curiouselytra-FORGE-1.15.2-2.0.jar |  
  | Cyclic | Lothrazar | Cyclic-1.15.2-0.4.1.jar |  
  | Cyclops Core | kroeser | CyclopsCore-1.15.2-1.6.2.jar |  
  | Dark Utilities | DarkhaxDev | DarkUtilities-1.15.2-3.0.5.jar |  
  | Dimensional Dungeons | Catastrophe573 | dimdungeons-1.051-forge-1.15.2.jar |  
  | Dungeon Crawl | XIROC1337 | DungeonCrawl-1.15.2-1.6.3.jar |  
  | Dungeons & Artifacts | dthovrlrd | dungeonsartifacts-1.15.2-V.1.2.5.jar |  
  | Dynamic World | technokamaster | dynamic_world-1.15.2-0.1.0.0.jar |  
  | Enchantable | MrCrayfish | enchantable-1.3.0-1.15.2.jar |  
  | Ender Magnet | Ruuubi | EnderMagnet-1.15.1-3.0.0.jar |  
  | Ender Mail | Chaosyr | EnderMail-1.15.2-1.1.0.jar |  
  | EnderChests | ShetiPhian | enderchests-1.15-1.6.0.jar |  
  | EnderTanks | ShetiPhian | endertanks-1.15-1.8.0.jar |  
  | Enhanced Anvil | HyCraftHD | enhanced_anvil-1.15.2-1.0.1.3.jar |  
  | Enigmatic Legacy | VictorShadow_ | EnigmaticLegacy-1.7.0.jar |  
  | Ensorcellation | TeamCoFH | ensorcellation-1.15.2-0.3.0b.jar |  
  | EverlastingAbilities | kroeser | EverlastingAbilities-1.15.2-1.6.1.jar |  
  | Extra Disks | MelanX | extradisks-1.15.1-1.2.jar |  
  | Fast Leaf Decay | olafskiii | FastLeafDecay-v22.jar |  
  | Flexible Skills Mod | MentaikoMod | flexible_skills-1.15.2-1.2.1-beta.jar |  
  | Flux (Forge Edition) | SH3VEK | flux-4.15.0.jar |  
  | Flux Library (FL) | SH3VEK | fl-3.2.2.jar |  
  | Flux Networks | sonar_sonic | FluxNetworks-1.15.2-5.0.1-2.jar |  
  | Forbidden and Arcanus | cesar_zorak | forbidden_arcanus-1.15.2-1.3.1.jar |  
  | Golden Hopper | MrCrayfish | goldenhopper-1.1.1-1.15.2.jar |  
  | GraveStone Mod | henkelmax | gravestone-1.17.4.jar |  
  | Harvest | Naxanria | harvest-1.15.2-1.0.1.jar |  
  | Industrial Foregoing | Buuz135 | industrial-foregoing-1.15.2-2.3.0-6f57752.jar |  
  | Infinite Trading | Serilum | inftrading_1.15.2-1.0.jar |  
  | Iron Chests | ProgWML6 | ironchest-1.15.2-10.0.3.jar |  
  | Iron Furnaces | XenoMustache | ironfurnaces-1.15.2-2.0.3.jar |  
  | Iron Jetpacks | BlakeBr0 | IronJetpacks-1.15.2-3.0.1.jar |  
  | Item Filters | LatvianModder | item-filters-2.2.0.14.jar |  
  | JAOPCA | TheLMiffy1111 | JAOPCA-1.15.2-3.2.0.9.jar |  
  | JEI Integration | SnowShock35 | jeiintegration_1.15.2-3.1.0.1.jar |  
  | JourneyMap | techbrew | journeymap-1.15.2-5.7.0b2.jar |  
  | Just Enough Items (JEI) | mezz | jei-1.15.2-6.0.0.4.jar |  
  | Kottle | Alex_wells | Kottle-1.5.2.jar |  
  | Large Fluid Tank | Kotori316 | LargeFluidTank-15.2.6.jar |  
  | Libnonymous | davenonymous | libnonymous-1.15.2-1.1.1.5.jar |  
  | Liroth | Decodinator_X | Liroth_1.15.2_7.3.8.jar |  
  | Lycanites Mobs | Lycanite | lycanitesmobs-1.15.2-2.2.3.2.jar |  
  | McJtyLib | McJty | mcjtylib-1.15-4.1.0-beta.jar |  
  | Mekanism | bradyaidanc | Mekanism-1.15.2-9.10.5.418.jar |  
  | Mekanism Additions | bradyaidanc | MekanismAdditions-1.15.2-9.10.5.418.jar |  
  | Mekanism Generators | bradyaidanc | MekanismGenerators-1.15.2-9.10.5.418.jar |  
  | Mekanism Tools | bradyaidanc | MekanismTools-1.15.2-9.10.5.418.jar |  
  | Metal Barrels | tfarecnim | metalbarrels-2.1.jar |  
  | Minions Mod | theluxure | minions_beta_1.0.1.jar |  
  | MixinBootstrap | LX_Gaming | MixinBootstrap-1.0.3.jar |  
  | MoreVanillaArmor | MelanX | morevanillaarmor-1.15.2-1.2.jar |  
  | Mouse Tweaks | YaLTeR | MouseTweaks-2.13-mc1.15.1.jar |  
  | Mutant Beasts | Chumbanotz | MutantBeasts-1.15.2-1.0.7.jar |  
  | Nature's Compass | Chaosyr | NaturesCompass-1.15.2-1.8.5.jar |  
  | nether+ | bmaster_gamer | nether+-1.7.5-1.15.2.jar |  
  | No Recipe Book | Seneschal_Luwin | noRecipeBook_v1.5.4formc1.15.2.jar |  
  | NoFog | Tommeh2 | NoFog-1.15b1.jar |  
  | Ore Excavation | Funwayguy | OreExcavation-1.7.151.jar |  
  | Pam's HarvestCraft 2 - Crops | pamharvestcraft | pamhc2crops-1.15.2-1.0.3.jar |  
  | Patchouli | Vazkii | Patchouli-1.15.2-1.2-33.jar |  
  | Placebo | Shadows_of_Fire | Placebo-1.15.2-3.0.2.jar |  
  | Prefab | wuestman | prefab-1.5.0.9.jar |  
  | Pretty Pipes | Ellpeck | PrettyPipes-1.5.1.jar |  
  | Project MMO | FishSound | Project MMO-1.15-2.35.1.jar |  
  | ProjectE | SinKillerJ | ProjectE-1.15.2-PE1.0.3B.jar |  
  | ProjectExtended | pupnewfster | ProjectExtended-1.15.2-1.1.0.jar |  
  | QuantumStorage | GigaBit101 | QuantumStorage-1.15.2-5.1.1.jar |  
  | Quark | Vazkii | Quark-r2.1-236.jar |  
  | RandomPatches | TheRandomLabs | randompatches-1.15.2-1.21.1.2.jar |  
  | Ranged Pumps | raoulvdberge | rangedpumps-0.7.1.jar |  
  | Refined Pipes | raoulvdberge | refinedpipes-0.4.1.jar |  
  | Refined Relocation 2 | BlayTheNinth | RefinedRelocation_1.15.2-7.1.1.jar |  
  | Refined Storage | raoulvdberge | refinedstorage-1.8.3.jar |  
  | Refined Storage Addons | raoulvdberge | refinedstorageaddons-0.6.1.jar |  
  | Reliquary v1.3 | P3pp3rF1y | Reliquary-1.15.2-1.3.4.995.jar |  
  | Repurposed Structures (Forge) | telepathicgrunt | repurposedstructures-1.15.2-1.4.1.jar |  
  | RFTools Base | McJty | rftoolsbase-1.15-1.1.1-beta.jar |  
  | RFTools Builder | McJty | rftoolsbuilder-1.15-2.1.1-beta.jar |  
  | RFTools Power | McJty | rftoolspower-1.15-2.1.1-beta.jar |  
  | RFTools Storage | McJty | rftoolsstorage-1.15-1.1.2-beta.jar |  
  | RFTools Utility | McJty | rftoolsutility-1.15-2.1.2-beta.jar |  
  | Rings of Ascension | Focamacho | RingsOfAscension-1.15.2-1.2.jar.disabled |  
  | Scalable Cat's Force | Kotori316 | ScalableCatsForce-2.13.2-build-2-with-library.jar |  
  | ShetiPhianCore | ShetiPhian | shetiphiancore-1.15-3.7.1.jar |  
  | Silent Lib | SilentChaos512 | SilentLib-1.15.2-4.6.1+49.jar |  
  | Silent's Mechanisms | SilentChaos512 | SilentMechanisms-1.15.2-0.7.1+51.jar |  
  | Simple Storage Network | Lothrazar | SimpleStorageNetwork-1.15.2-0.3.2.jar |  
  | Sound Filters | Tmtravlr | SoundFilters-0.13_for_1.15.2.jar |  
  | Speedy Hoppers | al132 | speedyhoppers-1.15.2-2.jar |  
  | Spice of Life: Carrot Edition | lordcazsius | solcarrot-1.15.2-1.9.4.jar |  
  | Storage Drawers | Texelsaur | StorageDrawers-1.15.2-7.0.2.jar |  
  | The Midnight | cipher_zero_x | themidnight-0.5.7-3.jar |  
  | The One Probe | McJty | theoneprobe-1.15-2.0.2.jar |  
  | Tirphycraft | LaZz_mod | tirphycraft-2.0.2.jar |  
  | Titanium | HRZNStudio | titanium-1.15.2-2.4.0.jar |  
  | Trample Stopper | UnRealDinnerbone | tramplestopper-1.15.2-2.0.0.1-universal.jar |  
  | Traveller's Boots | DenisMasterHerobrine | travellersboots-1.15.2-1.3.2.jar |  
  | U Team Core | HyCraftHD | u_team_core-1.15.2-2.11.0.156.jar |  
  | Ultra Amplified Dimension (Forge) | telepathicgrunt | ultra_amplified_dimension-1.15.2-7.4.2.jar |  
  | Valhelsia Structures | Khytwel | valhelsia_structures-15.0.2a.jar |  
  | Venture | MrCrayfish | venture-1.0.0-1.15.2.jar |  
  | Water Strainer | Ruuubi | WaterStrainer-1.15.2-9.0.0.jar |  
  | Waystones | BlayTheNinth | Waystones_1.15.2-6.0.1.jar |  
  | Wither Skeleton Tweaks | Shadows_of_Fire | WitherSkeletonTweaks-1.15.1-4.0.0.jar |  
  | ZmodSkills | Matixsss | Zmod 1.15.2-1.05.jar |

**Comment by MLMII** [comment] 2020-05-15 22:47
I also have the same issue; any chests that I enable possible ring generation are empty.

**Comment by Omni35** [comment] 2020-05-16 04:11
Can also confirm this being an issue, altho only if I have RingsOfAscension installed with even one of these mods:
**Botania (Botania-r1.15-384):** Chests in dungeons, mineshafts, end cities etc are empty
**Dragon Mounts Legacy (dragonmounts-1.0.3):** Same issue as Botania
**Corail Tombstone (tombstone-4.3.6-1.15.2):** RingsOfAscension seems to overwrite all Corail loot which would normally be in vanilla loot chests, sometimes the chest won't open right away and only the rings are generated beside vanilla loot

I've tested it with other mods that add items to vanilla loot chests and these work fine, seperately with just RoA as well as all together: Charm, Strange, Quark, Dungeon Crawl, Valhelsia Structures and Vanilla Food Pantry,

**Comment by Darkfiend009** [comment] 2020-05-17 23:35
I can confirm this as well.

**Comment by Focamacho** [comment] 2020-05-18 08:37
Thanks to everyone, it helped a lot.
I believe the bug was fixed in version 1.3 of rings of ascension.

**Comment by MLMII** [comment] 2020-05-21 20:55
This bug still exists in 1.4

**Comment by Focamacho** [comment] 2020-05-21 21:03
Can you send the logs, please?

**Comment by Focamacho** [comment] 2020-06-01 15:41
I can't replicate the bug, so I'll close it again.

**Closed by Focamacho** 2020-06-01 15:41 UTC
Labels: bug, missing info

**Comment by WolfShotz** [comment] 2020-06-11 14:02
Please note: This issue was apparent in DML because I was a moron and tried to modify chest loot tables using json alone. There is a way to modify chest loot tables without json, and using an event. This effectively allows you to add loot pools to a loot table. If you want an (albeit terrible) example:
https://github.com/WolfShotz/DML/blob/master/src/main/java/wolfshotz/dml/DragonMountsLegacy.java#L78

**Comment by Focamacho** [comment] 2020-06-11 14:49
@WolfShotz Hey! Thanks for the example but I think I can't use json files because I'm using some config files to change the loot chances based on the ring tier.
This was happening previously in Rigs of Ascension because I had forgotten to add a name to the LootPool, so when other mod tries to check the name/resourcelocation of the pool, it causes a null pointer exception.
I did some tests and everything seems to be working properly on Rings of Ascension 1.4.

**Comment by WolfShotz** [comment] 2020-06-11 17:30
Yeah, whenever it comes to chest loot tables I believe its best to avoid using jsons, unless you can somehow manage to get the new GlobalLootModifiers system to work with it, which I was unsuccessful
